Repository MFlowCode/MFC, pull requests merged in 2024-03, with the labels that each got.

#367 update perf in documentation
  docs/documentation/expectedPerformance.md
Labels: documentation, enhancement

#370 Website viz. - Links and descriptions
  docs/index.html
Labels: enhancement

#376 Upstream fixes and tools from Chemfc
  .github/workflows/docker.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/pretty.yml
  .github/workflows/spelling.yml
  .github/workflows/test.yml
  .gitignore
  .vscode/settings.json
  CMakeLists.txt
  README.md
  docs/documentation/case.md
  docs/documentation/getting-started.md
  mfc.sh
  src/post_process/m_start_up.f90
  src/pre_process/m_data_output.fpp
  src/simulation/m_global_parameters.fpp
  src/simulation/m_mpi_proxy.fpp
  src/simulation/m_rhs.fpp
  src/simulation/m_start_up.fpp
  toolchain/bootstrap/format.sh
  toolchain/mfc/build.py
  toolchain/mfc/common.py
  toolchain/mfc/run/case_dicts.py
  toolchain/mfc/run/input.py
Labels: bug, enhancement
