Repository MFlowCode/MFC, pull requests merged in 2024-11, with the labels that each got.

#682 Documentation updates
  docs/documentation/case.md
  docs/documentation/visualization.md
  docs/res/paraview.png
Labels: documentation

#694 aocc + turin
  docs/documentation/expectedPerformance.md
Labels: documentation

#695 bump python v
  toolchain/bootstrap/python.sh
Labels: bug

#713 Update Amd cpu speeds!
  docs/documentation/expectedPerformance.md
Labels: documentation

#704 Fix seg fault when fd_order is on
  src/simulation/m_global_parameters.fpp
Labels: bug, enhancement

#717 Don't always 'cleanliness'
  .github/workflows/cleanliness.yml
  .github/workflows/formatting.yml
  .github/workflows/line-count.yml
Labels: enhancement, continuous-integration

#718 Bump GH checkout CI action version
  .github/workflows/bench.yml
  .github/workflows/cleanliness.yml
  .github/workflows/test.yml
Labels: continuous-integration

#726 Update required CodeCov CI patch coverage for pass
  .github/codecov.yml
Labels: continuous-integration

#729 Faster Phoenix CPU benchmarking
  .github/workflows/phoenix/bench.sh
  benchmarks/5eq_rk3_weno3_hllc/case.py
  benchmarks/hypo_hll/case.py
  benchmarks/ibm/case.py
  benchmarks/viscous_weno5_sgb_acoustic/case.py
Labels: enhancement, continuous-integration

#732 Publish docs nightly
  .github/workflows/docs.yml
Labels: continuous-integration, website

#731 Shorter wall time for Phoenix benchmarking
  .github/workflows/phoenix/submit.sh
Labels: enhancement, continuous-integration

#734 Make the CI file filter more specific
  .github/file-filter.yml
  .github/workflows/bench.yml
Labels: continuous-integration

#738 ATOMIC commit that fixes a bug in the docs action event name
  .github/workflows/docs.yml
Labels: website

#698 GRCBC
  docs/documentation/case.md
  docs/documentation/references.md
  examples/2D_acoustic_pulse/case.py
  examples/2D_ibm_steady_shock/case.py
  examples/2D_zero_circ_vortex/case.py
  src/common/m_derived_types.fpp
  src/simulation/m_cbc.fpp
  src/simulation/m_checker.fpp
  src/simulation/m_global_parameters.fpp
  src/simulation/m_mpi_proxy.fpp
  src/simulation/m_start_up.fpp
  tests/0BDC8E40/golden-metadata.txt
  tests/0BDC8E40/golden.txt
  tests/212401B4/golden-metadata.txt
  tests/212401B4/golden.txt
  tests/38C2159F/golden-metadata.txt
  tests/38C2159F/golden.txt
  tests/63CD6ADF/golden-metadata.txt
  tests/63CD6ADF/golden.txt
  tests/D7107B89/golden-metadata.txt
  tests/D7107B89/golden.txt
  tests/EB6687AB/golden-metadata.txt
  tests/EB6687AB/golden.txt
  toolchain/mfc/run/case_dicts.py
  toolchain/mfc/test/cases.py
Labels: enhancement
