Repository MFlowCode/MFC, pull requests merged in 2024-12, with the labels that each got.

#752 Fix Chemistry advection fluxes
  examples/nD_perfect_reactor/case.py
  src/common/m_variables_conversion.fpp
  src/post_process/p_main.fpp
  src/simulation/m_chemistry.fpp
  src/simulation/m_rhs.fpp
  src/simulation/m_riemann_solvers.fpp
  tests/1550B67E/golden-metadata.txt
  tests/2BDE2018/golden-metadata.txt
  tests/2BDE2018/golden.txt
  tests/4D7D85B4/golden-metadata.txt
  tests/4D7D85B4/golden.txt
  tests/5DCF300C/golden-metadata.txt
  tests/6B3AE48F/golden-metadata.txt
  tests/6B3AE48F/golden.txt
  tests/E8372F50/golden-metadata.txt
  tests/F8ADA51B/golden-metadata.txt
  tests/F8ADA51B/golden.txt
  toolchain/mfc/build.py
Labels: bug

#756 Some minor CI improvements [readability]
  .github/workflows/formatting.yml
  .github/workflows/line-count.yml
  .github/workflows/lint-toolchain.yml
  .github/workflows/spelling.yml
Labels: continuous-integration

#760 Add performance of AMD Bergamo
  docs/documentation/expectedPerformance.md
Labels: documentation

#766 Fix linter for double precision MPI intrinsics and the offenders
  .github/workflows/lint-source.yml
  src/common/m_mpi_common.fpp
  src/pre_process/m_mpi_proxy.fpp
  src/simulation/m_mpi_proxy.fpp
Labels: enhancement, continuous-integration

#778 Clean up the linted source
  .github/workflows/lint-source.yml
  src/common/m_checker_common.fpp
  src/common/m_helper.fpp
  src/common/m_mpi_common.fpp
  src/common/m_phase_change.fpp
  src/post_process/m_data_input.f90
  src/pre_process/include/2dHardcodedIC.fpp
  src/pre_process/include/3dHardcodedIC.fpp
  src/pre_process/m_assign_variables.fpp
  src/pre_process/m_compute_levelset.fpp
  src/pre_process/m_grid.f90
  src/pre_process/m_model.fpp
  src/pre_process/m_patches.fpp
  src/pre_process/m_perturbation.fpp
  src/simulation/m_acoustic_src.fpp
  src/simulation/m_boundary_conditions.fpp
  src/simulation/m_fftw.fpp
  src/simulation/m_nvtx.f90
  src/simulation/m_qbmm.fpp
  src/simulation/m_sim_helpers.f90
Labels: enhancement, continuous-integration

#780 Finalizes some source code lint checks and automates them
  .fortitude.toml
  .github/workflows/lint-source.yml
  src/common/m_helper.fpp
  src/common/m_variables_conversion.fpp
  src/post_process/m_data_output.fpp
  src/pre_process/m_data_output.fpp
  src/pre_process/m_patches.fpp
  src/pre_process/m_perturbation.fpp
  src/simulation/m_bubbles_EL.fpp
  src/simulation/m_data_output.fpp
  src/simulation/m_hyperelastic.fpp
  src/simulation/m_qbmm.fpp
  src/simulation/m_start_up.fpp
  src/simulation/m_surface_tension.fpp
  toolchain/pyproject.toml
Labels: continuous-integration
