Repository MFlowCode/MFC, pull requests merged in 2025-07, with the labels that each got.

#910 Refactor `m_riemann_solvers` Module (HLL Solver)
  src/simulation/m_riemann_solvers.fpp
Labels: Review effort 3/5

#916 Fix #914
  src/post_process/m_mpi_proxy.fpp
Labels: Review effort 2/5

#920 Body Forces Bug Fix
  examples/2D_rayleigh_taylor/README.md
  examples/2D_rayleigh_taylor/final_condition.png
  examples/2D_rayleigh_taylor/linear_theory.png
  examples/2D_rayleigh_taylor/result.png
  src/simulation/m_body_forces.fpp
  tests/10041BB7/golden-metadata.txt
  tests/10041BB7/golden.txt
  tests/121D4ECA/golden-metadata.txt
  tests/121D4ECA/golden.txt
  tests/AE02324F/golden-metadata.txt
  tests/AE02324F/golden.txt
  tests/B54BB9D8/golden-metadata.txt
  tests/B54BB9D8/golden.txt
  tests/DEA0A0D6/golden-metadata.txt
  tests/DEA0A0D6/golden.txt
  tests/E21940B3/golden-metadata.txt
  tests/E21940B3/golden.txt
Labels: Review effort 2/5

#922 Create contributing.md
  .github/CONTRIBUTING.md
Labels: documentation, enhancement, Review effort 1/5

#883 Created FYPP macros to allow for meta-directive parallelization
  docs/documentation/gpuParallelization.md
  src/common/include/macros.fpp
  src/common/include/parallel_macros.fpp
  src/common/m_boundary_common.fpp
  src/common/m_chemistry.fpp
  src/common/m_finite_differences.fpp
  src/common/m_helper.fpp
  src/common/m_helper_basic.fpp
  src/common/m_mpi_common.fpp
  src/common/m_phase_change.fpp
  src/common/m_variables_conversion.fpp
  src/pre_process/m_assign_variables.fpp
  src/pre_process/m_patches.fpp
  src/simulation/include/inline_riemann.fpp
  src/simulation/m_acoustic_src.fpp
  src/simulation/m_body_forces.fpp
  src/simulation/m_bubbles.fpp
  src/simulation/m_bubbles_EE.fpp
  src/simulation/m_bubbles_EL.fpp
  src/simulation/m_bubbles_EL_kernels.fpp
  src/simulation/m_cbc.fpp
  src/simulation/m_compute_cbc.fpp
  src/simulation/m_data_output.fpp
  src/simulation/m_fftw.fpp
  src/simulation/m_global_parameters.fpp
  src/simulation/m_hyperelastic.fpp
  src/simulation/m_hypoelastic.fpp
  src/simulation/m_ibm.fpp
  src/simulation/m_mhd.fpp
  src/simulation/m_mpi_proxy.fpp
  src/simulation/m_pressure_relaxation.fpp
  src/simulation/m_qbmm.fpp
  src/simulation/m_rhs.fpp
  src/simulation/m_riemann_solvers.fpp
  src/simulation/m_sim_helpers.fpp
  src/simulation/m_start_up.fpp
  src/simulation/m_surface_tension.fpp
  src/simulation/m_time_steppers.fpp
  src/simulation/m_viscous.fpp
  src/simulation/m_weno.fpp
Labels: Review effort 4/5

#933 Update actions to minimize node use.
  .github/workflows/bench.yml
  .github/workflows/phoenix/bench.sh
  .github/workflows/phoenix/submit-bench.sh
  .github/workflows/phoenix/submit.sh
  .github/workflows/phoenix/test.sh
  .github/workflows/test.yml
  misc/starting-phoenix-runners.md
Labels: Review effort 1/5

#940 Make vscode a bit nicer [fewer spurious warnings or errors]
  .fortls.json
  .fortlsrc
  .vscode/extensions.json
  .vscode/settings.json
Labels: Review effort 2/5

#850 Replace intrinsics in allocate statements
  src/common/m_derived_types.fpp
  src/common/m_helper_basic.fpp
  src/common/m_mpi_common.fpp
  src/common/m_variables_conversion.fpp
  src/post_process/m_global_parameters.fpp
  src/post_process/m_start_up.f90
  src/pre_process/m_global_parameters.fpp
  src/pre_process/m_start_up.fpp
  src/simulation/m_global_parameters.fpp
  src/simulation/m_mpi_proxy.fpp
  src/simulation/m_pressure_relaxation.fpp
  src/simulation/m_riemann_solvers.fpp
  src/simulation/m_start_up.fpp
  src/simulation/m_viscous.fpp
Labels: Review effort 3/5

#941 Removes the macros t_vec3 and the t_4x4 matrix one
  src/common/include/macros.fpp
  src/common/m_derived_types.fpp
  src/common/m_helper.fpp
  src/pre_process/m_model.fpp
  src/pre_process/m_patches.fpp
Labels: Review effort 2/5

#930 Lint Check for Raw Directives
  .github/workflows/lint-source.yml
Labels: Review effort 2/5

#938 Bug fix in m_data_input.f90
  src/post_process/m_data_input.f90
Labels: Review effort 2/5

#947 fix docs
  docs/documentation/case.md
Labels: Review effort 1/5

#956 Fix some documentation links
  docs/documentation/case.md
  docs/documentation/getting-started.md
  examples/2D_lid_driven_cavity/README.md
  examples/nD_perfect_reactor/README.md
  examples/scaling/README.md
Labels: Review effort 1/5

#958 update cursor rules [typo fixes]
  .cursor/rules/mfc-agent-rules.mdc
Labels: Review effort 2/5

#962 Fixed rendering on GPU debug page
  docs/documentation/gpuDebugging.md
Labels: bug, documentation, Review effort 1/5

#964 Probe WRT on GPUs
  src/simulation/m_checker.fpp
  src/simulation/m_derived_variables.fpp
  src/simulation/m_time_steppers.fpp
Labels: Review effort 4/5

#963 bubbles clean-up: remove `R0_type` and `V0`
  docs/documentation/case.md
  examples/1D_poly_bubscreen/case.py
  examples/1D_qbmm/case.py
  examples/2D_bubbly_steady_shock/case.py
  examples/2D_whale_bubble_annulus/case.py
  src/post_process/m_global_parameters.fpp
  src/pre_process/m_assign_variables.fpp
  src/pre_process/m_checker.fpp
  src/pre_process/m_global_parameters.fpp
  src/pre_process/m_mpi_proxy.fpp
  src/pre_process/m_start_up.fpp
  src/simulation/m_global_parameters.fpp
  src/simulation/m_mpi_proxy.fpp
  src/simulation/m_start_up.fpp
  toolchain/mfc/run/case_dicts.py
  toolchain/mfc/test/case.py
Labels: Review effort 3/5
