Repository MFlowCode/MFC, pull requests merged in 2025-06, with the labels that each got.

#897 Creates `.toml` for auto reviewing PRs
  .pr_agent.toml
Labels: Review effort 1/5

#898 PR agent for qodo
  .pr_agent.toml
Labels: Review effort 1/5

#903 add carpenter cray modules
  toolchain/bootstrap/modules.sh
  toolchain/modules
  toolchain/templates/carpenter-cray.mako
Labels: Review effort 2/5

#904 Fix Skipped Test Issue
  toolchain/mfc/test/test.py
Labels: Review effort 2/5

#902 Refac data input - Post process
  src/post_process/m_data_input.f90
Labels: Review effort 3/5

#906 Fix temp benchmark directory
  .github/workflows/frontier/build.sh
  .github/workflows/frontier/submit.sh
  .github/workflows/frontier/test.sh
  .github/workflows/phoenix/bench.sh
  .github/workflows/phoenix/submit-bench.sh
  .github/workflows/phoenix/submit.sh
  .github/workflows/phoenix/test.sh
Labels: Review effort 2/5
